
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    networks:
      - order-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  ordermanagement-api:
    container_name: ordermanagement-api
    build:
      context: .
      dockerfile: OrderManagement.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=ordersdb;Username=postgres;Password=postgres"
      ServiceBus__ConnectionString: "todo"
      ServiceBus__QueueName: "orders"
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
    networks:
      - order-net

  orders-frontend:
    container_name: orders-frontend
    build:
      context: ./orders-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - order-net
    depends_on:
      - ordermanagement-api
    environment:
      REACT_APP_API_URL: "http://ordermanagement-api:8080"

networks:
  order-net:
volumes:
  pgdata:
